import { BodyScanRecord } from './types';
import { computeFullBiomarkers } from './bodymap-engine';

const maleMeasurementsT1 = {
  neck: 39.5,
  chest: 104.0,
  waist: 86.5,
  abdomen: 89.0,
  hips: 99.5,
  bicepsRight: 37.0,
  bicepsLeft: 36.6,
  forearmRight: 29.5,
  forearmLeft: 29.2,
  thighRight: 59.0,
  thighLeft: 58.6,
  calfRight: 38.0,
  calfLeft: 37.8,
};

const maleMeasurementsT2 = {
  neck: 40.0,
  chest: 106.5,
  waist: 81.5,
  abdomen: 83.0,
  hips: 98.0,
  bicepsRight: 38.5,
  bicepsLeft: 38.3,
  forearmRight: 30.2,
  forearmLeft: 30.0,
  thighRight: 61.0,
  thighLeft: 60.8,
  calfRight: 38.5,
  calfLeft: 38.4,
};

const femaleMeasurementsT1 = {
  neck: 32.5,
  chest: 90.0,
  waist: 73.0,
  abdomen: 78.5,
  hips: 103.0,
  bicepsRight: 27.5,
  bicepsLeft: 27.2,
  forearmRight: 23.0,
  forearmLeft: 22.8,
  thighRight: 58.5,
  thighLeft: 58.0,
  calfRight: 35.5,
  calfLeft: 35.3,
};

const femaleMeasurementsT2 = {
  neck: 32.0,
  chest: 88.5,
  waist: 67.5,
  abdomen: 71.0,
  hips: 98.5,
  bicepsRight: 28.2,
  bicepsLeft: 28.0,
  forearmRight: 23.4,
  forearmLeft: 23.2,
  thighRight: 56.5,
  thighLeft: 56.2,
  calfRight: 35.0,
  calfLeft: 35.0,
};

export const sampleScans: BodyScanRecord[] = [
  {
    id: 'scan-m1-baseline',
    patientId: 'pac-lucas-silva',
    patientName: 'Lucas Silva (Atleta CrossFit)',
    age: 29,
    sex: 'male',
    heightCm: 181,
    weightKg: 85.4,
    scanDate: '2026-06-15',
    measurements: maleMeasurementsT1,
    biomarkers: computeFullBiomarkers('male', 29, 181, 85.4, maleMeasurementsT1),
    posture: {
      shoulderTiltDegrees: 1.2,
      pelvicTiltDegrees: 0.8,
      headForwardTiltMm: 12,
      notes: ['Leve elevação do ombro direito', 'Alinhamento pélvico dentro da normalidade'],
    },
    confidenceScorePercent: 98.8,
    clinicalNotes: 'Scan de linha de base (T0). Foco em redução de gordura visceral e recomposição corporal.',
  },
  {
    id: 'scan-m1-followup',
    patientId: 'pac-lucas-silva',
    patientName: 'Lucas Silva (Atleta CrossFit)',
    age: 29,
    sex: 'male',
    heightCm: 181,
    weightKg: 83.2,
    scanDate: '2026-09-18',
    measurements: maleMeasurementsT2,
    biomarkers: computeFullBiomarkers('male', 29, 181, 83.2, maleMeasurementsT2),
    posture: {
      shoulderTiltDegrees: 0.4,
      pelvicTiltDegrees: 0.2,
      headForwardTiltMm: 6,
      notes: ['Melhora postural evidente na cadeia posterior', 'Simetria escapular restabelecida'],
    },
    confidenceScorePercent: 99.2,
    clinicalNotes: 'Scan de reavaliação (T1 - 90 dias). Redução de 5cm de cintura e ganho de massa magra nos membros.',
  },
  {
    id: 'scan-f1-baseline',
    patientId: 'pac-marina-costa',
    patientName: 'Marina Costa (Recomposição Corporal)',
    age: 34,
    sex: 'female',
    heightCm: 167,
    weightKg: 66.8,
    scanDate: '2026-05-10',
    measurements: femaleMeasurementsT1,
    biomarkers: computeFullBiomarkers('female', 34, 167, 66.8, femaleMeasurementsT1),
    posture: {
      shoulderTiltDegrees: -0.9,
      pelvicTiltDegrees: 1.4,
      headForwardTiltMm: 15,
      notes: ['Hiperlordose lombar compensatória', 'Ombro esquerdo ligeiramente deprimido'],
    },
    confidenceScorePercent: 98.4,
    clinicalNotes: 'Avaliação inicial para protocolo hipertrofia e definição glútea.',
  },
  {
    id: 'scan-f1-followup',
    patientId: 'pac-marina-costa',
    patientName: 'Marina Costa (Recomposição Corporal)',
    age: 34,
    sex: 'female',
    heightCm: 167,
    weightKg: 62.4,
    scanDate: '2026-09-15',
    measurements: femaleMeasurementsT2,
    biomarkers: computeFullBiomarkers('female', 34, 167, 62.4, femaleMeasurementsT2),
    posture: {
      shoulderTiltDegrees: -0.2,
      pelvicTiltDegrees: 0.5,
      headForwardTiltMm: 7,
      notes: ['Correção de báscula pélvica significativa', 'Alinhamento cervical normalizado'],
    },
    confidenceScorePercent: 99.1,
    clinicalNotes: 'Reavaliação de 120 dias: Perda de 4.4kg com preservação de massa magra e afunilamento de cintura.',
  },
];
